import type { QuestionDefinition } from "@/types/assessment";

export const SCREENING_QUESTIONS: QuestionDefinition[] = [
  {
    id: "owns_buildings",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company own or control buildings?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope1_stationary", "scope2_electricity", "scope2_heat", "scope1_refrigerants", "scope3_waste"] }],
  },
  {
    id: "operates_manufacturing",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company operate manufacturing facilities?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope1_process", "scope1_stationary", "scope2_electricity"] }],
  },
  {
    id: "owns_vehicles",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company own or lease vehicles?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope1_mobile"] }],
  },
  {
    id: "burns_fuels",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company burn natural gas, diesel, LPG or other fuels?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope1_stationary", "scope1_mobile"] }],
  },
  {
    id: "uses_refrigeration",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company use refrigeration or air-conditioning equipment?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope1_refrigerants"] }],
  },
  {
    id: "purchases_electricity",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company purchase electricity?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope2_electricity"] }],
  },
  {
    id: "purchases_heat",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company purchase heating, cooling or steam?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope2_heat"] }],
  },
  {
    id: "purchases_goods",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company purchase physical goods or raw materials?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_purchased_goods", "scope3_upstream_transport"] }],
  },
  {
    id: "purchases_services",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company purchase external services?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_purchased_goods"] }],
  },
  {
    id: "generates_waste",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company generate waste?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_waste"] }],
  },
  {
    id: "employees_travel",
    section: "operational_screening",
    type: "boolean",
    label: "Do employees travel for business?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_business_travel"] }],
  },
  {
    id: "employees_commute",
    section: "operational_screening",
    type: "boolean",
    label: "Do employees commute to a workplace?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_commuting"] }],
  },
  {
    id: "transports_products",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company transport products?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_upstream_transport", "scope3_downstream_transport"] }],
  },
  {
    id: "sells_physical_products",
    section: "operational_screening",
    type: "boolean",
    label: "Does your company sell physical products?",
    required: true,
    activates: [{ when: { equals: true }, modules: ["scope3_downstream_transport"] }],
  },
];
