/**
 * Multi-page CSRD / GHG summary PDF (client or server safe).
 * Minimal PDF writer — no paid services; open format.
 */

export type CsrdPdfInput = {
  companyName: string;
  periodLabel: string;
  generatedAt: string;
  totalTCO2e: number;
  scope1: number;
  scope2: number;
  scope3: number;
  activityCount: number;
  verifiedPct: number;
  targetName?: string;
  targetYear?: number;
  targetReductionPct?: number;
  baselineTCO2e?: number;
  categories: { name: string; tCO2e: number }[];
  initiatives: { name: string; status: string; reduction: number }[];
  facilities: { name: string; country: string; tCO2e: number }[];
};

function esc(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function pageContent(lines: string[], title: string, pageNo: number, pageCount: number) {
  const ops: string[] = [
    "BT",
    "/F1 14 Tf",
    "50 760 Td",
    "16 TL",
    `(${esc(title)}) Tj`,
    "T*",
    "/F1 9 Tf",
    "12 TL",
    `(Qlimwelt · page ${pageNo}/${pageCount}) Tj`,
    "T*",
    "T*",
  ];
  for (const line of lines.slice(0, 48)) {
    ops.push(`(${esc(line)}) Tj`, "T*");
  }
  ops.push("ET");
  return ops.join("\n");
}

/** Build a multi-page PDF document as a string (binary-safe ASCII for Helvetica text). */
export function buildCsrdPdf(input: CsrdPdfInput): string {
  const pages: { title: string; lines: string[] }[] = [];

  pages.push({
    title: "CSRD / GHG Inventory Summary",
    lines: [
      `Company: ${input.companyName}`,
      `Period: ${input.periodLabel}`,
      `Generated: ${input.generatedAt}`,
      "",
      "1. Executive summary",
      `Total GHG emissions: ${input.totalTCO2e.toFixed(2)} tCO2e`,
      `Scope 1 (direct): ${input.scope1.toFixed(2)} tCO2e`,
      `Scope 2 (energy): ${input.scope2.toFixed(2)} tCO2e`,
      `Scope 3 (value chain): ${input.scope3.toFixed(2)} tCO2e`,
      `Activity records: ${input.activityCount}`,
      `Verified share: ${input.verifiedPct.toFixed(1)}%`,
      "",
      "This document summarises inventory metrics for internal disclosure drafting.",
      "It is not a full ESRS E1 assurance package; attach primary evidence separately.",
    ],
  });

  pages.push({
    title: "ESRS E1 — Climate targets",
    lines: [
      `Target: ${input.targetName ?? "Not set"}`,
      `Target year: ${input.targetYear ?? "—"}`,
      `Reduction commitment: ${input.targetReductionPct ?? "—"}%`,
      `Baseline emissions: ${input.baselineTCO2e?.toFixed(2) ?? "—"} tCO2e`,
      "",
      "Pathway notes:",
      "- Absolute reduction pathway assumed unless intensity target is configured.",
      "- Progress should be recalculated after each inventory refresh.",
      "",
      "Governance (draft checklist):",
      "[ ] Board oversight of climate targets documented",
      "[ ] Transition plan linked to CapEx / OpEx",
      "[ ] Scope 3 categories materiality assessment attached",
    ],
  });

  const catLines = input.categories.length
    ? input.categories.slice(0, 30).map((c) => `  ${c.name}: ${c.tCO2e.toFixed(2)} tCO2e`)
    : ["  No category breakdown available"];
  pages.push({
    title: "Emissions by category",
    lines: ["Material category totals (filtered inventory):", "", ...catLines],
  });

  const facLines = input.facilities.length
    ? input.facilities.slice(0, 25).map((f) => `  ${f.name} (${f.country}): ${f.tCO2e.toFixed(2)} tCO2e`)
    : ["  No facility allocation available"];
  pages.push({
    title: "Facility allocation",
    lines: ["Emissions attributed by facility:", "", ...facLines],
  });

  const initLines = input.initiatives.length
    ? input.initiatives
        .slice(0, 25)
        .map((i) => `  [${i.status}] ${i.name} — ${i.reduction} tCO2e/yr`)
    : ["  No initiatives recorded"];
  pages.push({
    title: "Reduction initiatives",
    lines: [
      "Planned and in-progress abatement:",
      "",
      ...initLines,
      "",
      "End of report — generated by Qlimwelt.",
    ],
  });

  const pageCount = pages.length;
  const contentStreams = pages.map((p, i) => pageContent(p.lines, p.title, i + 1, pageCount));

  const objects: string[] = [];
  // 1 catalog, 2 pages, 3..n+2 page objs, then contents, then font
  const pageObjStart = 3;
  const contentObjStart = pageObjStart + pageCount;
  const fontObj = contentObjStart + pageCount;

  objects.push(`1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj`);
  const kids = Array.from({ length: pageCount }, (_, i) => `${pageObjStart + i} 0 R`).join(" ");
  objects.push(`2 0 obj<< /Type /Pages /Kids [${kids}] /Count ${pageCount} >>endobj`);

  for (let i = 0; i < pageCount; i++) {
    const contentRef = contentObjStart + i;
    objects.push(
      `${pageObjStart + i} 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${contentRef} 0 R /Resources << /Font << /F1 ${fontObj} 0 R >> >> >>endobj`
    );
  }
  for (let i = 0; i < pageCount; i++) {
    const stream = contentStreams[i];
    objects.push(
      `${contentObjStart + i} 0 obj<< /Length ${stream.length} >>stream\n${stream}\nendstream\nendobj`
    );
  }
  objects.push(`${fontObj} 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj`);

  const encoder = new TextEncoder();
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(encoder.encode(pdf).length);
    pdf += obj + "\n";
  }
  const xrefStart = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < offsets.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return pdf;
}
